const cards = [
  {
    name: "Chezu Sushi",
    image: "images/ChezuSushi.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Sushi",
  },
  {
    name: "Originale Sushi",
    image: "images/OriginaleSushi.svg",
    rating: 4.8,
    price: "$21.00",
    category: "Sushi",
  },
  {
    name: "Ramen Legendo",
    image: "images/RamenLegendo.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Ramen",
  },
  {
    name: "Tofu Sushi",
    image: "images/ChezuSushi.svg",
    rating: 5.0,
    price: "$12.00",
    category: "Sushi",
  },
  {
    name: "Spice Sushi",
    image: "images/OriginaleSushi.svg",
    rating: 4.6,
    price: "$22.00",
    category: "Sushi",
  },
  {
    name: "Spicy Ramen",
    image: "images/RamenLegendo.svg",
    rating: 4.9,
    price: "$23.00",
    category: "Ramen",
  },
  {
    name: "Ramen Umo",
    image: "images/RamenLegendo.svg",
    rating: 4.5,
    price: "$15.00",
    category: "Ramen",
  },
  {
    name: "Udon Classic",
    image: "images/popular-udon.svg",
    rating: 4.5,
    price: "$20.00",
    category: "Udon",
  },
  {
    name: "Udon Spicy",
    image: "images/popular-udon.svg",
    rating: 4.5,
    price: "$21.00",
    category: "Udon",
  },
  {
    name: "Udon with Shrimps",
    image: "images/popular-udon.svg",
    rating: 5.0,
    price: "$25.00",
    category: "Udon",
  },
  {
    name: "Udon with Tofu",
    image: "images/popular-udon.svg",
    rating: 4.5,
    price: "$18.00",
    category: "Udon",
  },
  {
    name: "Original Danggo",
    image: "images/popular-danggo.svg",
    rating: 4.9,
    price: "$13.00",
    category: "Danggo",
  },
  {
    name: "Spicy Danggo",
    image: "images/popular-danggo.svg",
    rating: 4.8,
    price: "$14.00",
    category: "Danggo",
  },
  {
    name: "Tofu Danggo",
    image: "images/popular-danggo.svg",
    rating: 4.7,
    price: "$11.00",
    category: "Danggo",
  },
  {
    name: "Salmon Danggo",
    image: "images/popular-danggo.svg",
    rating: 5.0,
    price: "$18.00",
    category: "Danggo",
  },
  {
    name: "Vegetable Danggo",
    image: "images/popular-danggo.svg",
    rating: 4.6,
    price: "$12.00",
    category: "Danggo",
  },
  {
    name: "Box with Fish",
    image: "https://www.svgrepo.com/show/244419/sushi.svg",
    rating: 4.8,
    price: "$25.00",
    category: "Others",
  },
  {
    name: "Sauce Tabasco",
    image: "https://www.svgrepo.com/show/244420/tabasco.svg",
    rating: 4.9,
    price: "$2.00",
    category: "Others",
  },
  {
    name: "Japanice Icecream",
    image: "https://www.svgrepo.com/show/244447/ice-cream.svg",
    rating: 4.9,
    price: "$10.00",
    category: "Others",
  },
];
