export const menuItems = [
  {
    name: "Chezu Sushi",
    image: "images/ChezuSushi.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Sushi",
  },
  {
    name: "Originale Sushi",
    image: "images/OriginaleSushi.svg",
    rating: 4.8,
    price: "$21.00",
    category: "Sushi",
  },
  {
    name: "Ramen Legendo",
    image: "images/RamenLegendo.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Ramen",
  },
  {
    name: "Shrimp Sushi",
    image: "images/sushi-shrimp.svg",
    rating: 4.7,
    price: "$21.00",
    category: "Sushi",
  },
  {
    name: "Spicy Tofu",
    image: "images/Spice-Tofu.svg",
    rating: 5.0,
    price: "$15.00",
    category: "Sushi",
  },
  {
    name: "Salmon Maki",
    image: "images/trendy1.svg",
    rating: 4.8,
    price: "$15.00",
    category: "Sushi",
  },
  {
    name: "Udon Classic",
    image: "images/popular-udon.svg",
    rating: 4.5,
    price: "$20.00",
    category: "Udon",
  },
  {
    name: "Salmon Steak",
    image: "images/sushi-salmon.svg",
    rating: 4.9,
    price: "$20.00",
    category: "Others",
  },
  {
    name: "Original Danggo",
    image: "images/popular-danggo.svg",
    rating: 4.9,
    price: "$13.00",
    category: "Danggo",
  },
  {
    name: "Botchan Danggo",
    image: "images/Botchan-danggo.svg",
    rating: 4.8,
    price: "$14.00",
    category: "Danggo",
  },
  {
    name: "Spicy Danggo",
    image: "images/spicy-danggo.svg",
    rating: 4.9,
    price: "$13.00",
    category: "Danggo",
  },
];
