export const menuItems = [
  {
    name: "Chezu Sushi",
    image: "images/menuImages/chezuSushi.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Sushi",
  },
  {
    name: "Originale Sushi",
    image: "images/menuImages/originaleSushi.svg",
    rating: 4.8,
    price: "$21.00",
    category: "Sushi",
  },
  {
    name: "Ramen Legendo",
    image: "images/menuImages/ramenLegendo.svg",
    rating: 4.7,
    price: "$16.00",
    category: "Ramen",
  },
  {
    name: "Ramen with egg",
    image: "images/menuImages/ramenWithEgg.svg",
    rating: 4.8,
    price: "$18.00",
    category: "Ramen",
  },
  {
    name: "Sashimi Ramen",
    image: "images/menuImages/sashimiRamen.svg",
    rating: 5.0,
    price: "$21.00",
    category: "Ramen",
  },
  {
    name: "Naruto Ramen",
    image: "images/menuImages/narutoRamen.svg",
    rating: 5.0,
    price: "$25.00",
    category: "Ramen",
  },
  {
    name: "Shrimp Sushi",
    image: "images/menuImages/shrimpSushi.svg",
    rating: 4.7,
    price: "$21.00",
    category: "Sushi",
  },
  {
    name: "Salmon Sushi",
    image: "images/menuImages/salmonSushi.svg",
    rating: 4.9,
    price: "$18.00",
    category: "Sushi",
  },
  {
    name: "Spicy Tofu",
    image: "images/menuImages/spicyTofuSushi.svg",
    rating: 5.0,
    price: "$15.00",
    category: "Sushi",
  },
  {
    name: "Salmon Maki",
    image: "images/menuImages/salmonMakiSushi.svg",
    rating: 4.8,
    price: "$15.00",
    category: "Sushi",
  },
  {
    name: "Udon Classic",
    image: "images/menuImages/udonClassic.svg",
    rating: 4.5,
    price: "$20.00",
    category: "Udon",
  },
  {
    name: "Udon Spicy",
    image: "images/menuImages/spicyUdon.svg",
    rating: 4.6,
    price: "$21.00",
    category: "Udon",
  },
  {
    name: "Udon with Egg",
    image: "images/menuImages/udonWithEgg.svg",
    rating: 4.5,
    price: "$18.00",
    category: "Udon",
  },
  {
    name: "Salmon Steak",
    image: "images/menuImages/salmonSteak.svg",
    rating: 4.9,
    price: "$20.00",
    category: "Others",
  },
  {
    name: "Kappa Maki",
    image: "images/menuImages/kappaMakiSushi.svg",
    rating: 5.0,
    price: "$18.00",
    category: "Others",
  },
  {
    name: "Tekka Maki",
    image: "images/menuImages/tekkaMakiSushi.svg",
    rating: 4.8,
    price: "$19.00",
    category: "Others",
  },
  {
    name: "Botchan Danggo",
    image: "images/menuImages/botchanDanggo.svg",
    rating: 4.8,
    price: "$14.00",
    category: "Danggo",
  },
  {
    name: "Original Danggo",
    image: "images/menuImages/originalDanggo.svg",
    rating: 4.9,
    price: "$13.00",
    category: "Danggo",
  },
  {
    name: "Spicy Danggo",
    image: "images/menuImages/spicyDanggo.svg",
    rating: 4.9,
    price: "$13.00",
    category: "Danggo",
  },
];
